trigger:
  branches:
    include:
    - master
    - releases/*
    - azure-pipelines-testing/*

pr:
  branches:
    include:
    - master
    - releases/*
    exclude:
    - releases/old*

pool:
  vmImage: 'vs2017-win2016'

variables:
  containerTag: netfx-4.7.2-dotnet-2.1-webtools
  pushToRegistry: netfx-4.7.2-dotnet-2.1-webtools

steps:
- task: PowerShell@2
  displayName: 'docker build'
  inputs:
    targetType: 'filePath'
    filePath: $(Build.SourcesDirectory)\msbuild\Build-SingleContainer.ps1
    arguments: '-ContainerTag "netfx-4.7.2-dotnet-2.1-webtools"'
    workingDirectory: $(Build.SourcesDirectory)\msbuild
